=== dnlrs/dp2/assignment_1a/Assignment1a/dtd/nfvInfo.dtd
<!-- ====================================================================== -->
<!-- Assignment 1                                                           -->
<!--                                                                        -->
<!-- @author    Daniel C. Rusu                                              -->
<!-- @studentID 234428                                                      -->
<!-- ============================================= XML DTD ================ -->

<!-- DTD for nfvInfo system -->

<!ELEMENT NFVSystem (IN, catalogue, deployedNFFGs)>

  <!ELEMENT IN (hosts, connections)>


    <!ELEMENT hosts (host+)>
      <!ELEMENT host (maxVNFs, installedMemory, installedStorage, allocatedNodes)>
      <!ATTLIST host
                  name    ID         #REQUIRED> <!-- [1] -->
        
        <!ELEMENT maxVNFs (#PCDATA)>
        <!ELEMENT installedMemory (#PCDATA)>
        <!ATTLIST installedMemory
                    unit    NMTOKEN    #FIXED "MB">
        <!ELEMENT installedStorage (#PCDATA)>
        <!ATTLIST installedStorage
                    unit    NMTOKEN    #FIXED "MB">
        
        <!ELEMENT allocatedNodes (anode*)>
          <!ELEMENT anode (#PCDATA)>
        
        
    <!ELEMENT connections (connection+)>

      <!ELEMENT connection (connectionID, averageThroughput, latency)>
        <!ELEMENT connectionID EMPTY>
        <!ATTLIST connectionID
                    sourceHost      IDREF    #REQUIRED 
                    destinationHost IDREF    #REQUIRED> <!-- [5] -->
        <!ELEMENT averageThroughput (#PCDATA)>
        <!ATTLIST averageThroughput
                    unit    NMTOKEN    #FIXED "Mbps">
        <!ELEMENT latency (#PCDATA)>
        <!ATTLIST latency
                    unit    NMTOKEN    #FIXED "ms">
                     



  <!ELEMENT catalogue (vnf*)>
  
    <!ELEMENT vnf (requiredMemory, requiredStorage)>
    <!ATTLIST vnf
                name           ID                                                                         #REQUIRED 
                functionalType (CACHE|DPI|FW|MAIL_CLIENT|MAIL_SERVER|NAT|SPAM|VPN|WEB_CLIENT|WEB_SERVER)  #REQUIRED> <!-- [4] -->
      <!ELEMENT requiredMemory (#PCDATA)>
      <!ATTLIST requiredMemory
                  unit    NMTOKEN    #FIXED "MB">
      <!ELEMENT requiredStorage (#PCDATA)>
      <!ATTLIST requiredStorage
                  unit    NMTOKEN    #FIXED "MB">
    
    
    
    
    
  <!ELEMENT deployedNFFGs (nffg*)>
    
    <!ELEMENT nffg (deployTime, nodes)>
    <!ATTLIST nffg
                name    ID    #REQUIRED> <!-- [2] -->
    <!ELEMENT deployTime (#PCDATA)>
    <!ELEMENT nodes (node*)>
      <!ELEMENT node (hostingHost, functionalType, associatedNFFG, links)>
      <!ATTLIST node
                  name    ID    #REQUIRED> <!-- [3] -->
   
        <!ELEMENT hostingHost EMPTY>
        <!ATTLIST hostingHost
                    name    IDREF    #REQUIRED> <!-- [7] -->
        <!ELEMENT functionalType EMPTY>
        <!ATTLIST functionalType
                    type    IDREF    #REQUIRED> <!-- [8] -->
        <!ELEMENT associatedNFFG EMPTY>
        <!ATTLIST associatedNFFG
                    name    IDREF    #REQUIRED> <!-- [9] -->
        <!ELEMENT links (link*)>
          <!ELEMENT link (minThroughput?, maxLatency?)>
          <!ATTLIST link
                      name               NMTOKEN  #REQUIRED
                      sourceNode         IDREF    #REQUIRED
                      destinationNode    IDREF    #REQUIRED> <!-- [6] -->
                      
            <!ELEMENT minThroughput (#PCDATA)>
            <!ATTLIST minThroughput
                        unit    NMTOKEN    #FIXED "Mbps">
            <!ELEMENT maxLatency (#PCDATA)>
            <!ATTLIST maxLatency
                        unit    NMTOKEN    #FIXED "ms">

=== dnlrs/dp2/assignment1/dtd/nfvInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nfvInfo SYSTEM "nfvInfo.dtd">

<!-- ====================================================================== -->
<!-- Assignment 1                                                           -->
<!--                                                                        -->
<!-- @author    Daniel C. Rusu                                              -->
<!-- @studentID 234428                                                      -->
<!-- ==================================== DTD-validated XML =============== -->

<NFVSystem>

 <IN>
  <hosts>
   <host name="host1">
    <maxVNFs>5</maxVNFs>
    <installedMemory unit="MB">4096</installedMemory>
    <installedStorage unit="MB">1024000</installedStorage>
    <allocatedNodes>
     <anode>node1</anode>
     <anode>node2</anode>
     <anode>node3</anode>
    </allocatedNodes>
   </host>
   <host name="host2">
    <maxVNFs>10</maxVNFs>
    <installedMemory unit="MB">4096</installedMemory>
    <installedStorage unit="MB">1024000</installedStorage>
    <allocatedNodes>
     <anode>node4</anode>
     <anode>node5</anode>
    </allocatedNodes>
   </host>
  </hosts>
  
  <connections>
   <connection>
    <connectionID sourceHost="host1" destinationHost="host2"/>
    <averageThroughput unit="Mbps">40.0</averageThroughput>
    <latency unit="ms">50</latency>
   </connection>
   <connection>
    <connectionID sourceHost="host2" destinationHost="host1"/>
    <averageThroughput unit="Mbps">40.0</averageThroughput>
    <latency unit="ms">50</latency>
   </connection>
  </connections>
 </IN>
 
 <catalogue>
  <vnf name="webclient" functionalType="WEB_CLIENT">
   <requiredMemory unit="MB">256</requiredMemory>
   <requiredStorage unit="MB">25</requiredStorage>
  </vnf>
  <vnf name="webserver" functionalType="WEB_SERVER">
   <requiredMemory unit="MB">512</requiredMemory>
   <requiredStorage unit="MB">160</requiredStorage>
  </vnf>
 </catalogue>

 <deployedNFFGs>
  <nffg name="nffg1">
   <deployTime>2017-11-11T10:00:00+01:00</deployTime>
   <nodes>
    <node name="node1">
     <hostingHost name="host1"/>
     <functionalType type="webclient"/>
     <associatedNFFG name="nffg1"/>
     <links>
      <link name="link1" sourceNode="node1" destinationNode="node2">
       <minThroughput unit="Mbps">20.0</minThroughput>
       <maxLatency unit="ms">100</maxLatency>
      </link>
     </links>
    </node>
    <node name="node2">
     <hostingHost name="host1"/>
     <functionalType type="webclient"/>
     <associatedNFFG name="nffg1"/>
     <links>
      <link name="link2" sourceNode="node2" destinationNode="node1">
       <minThroughput unit="Mbps">20.0</minThroughput>
       <maxLatency unit="ms">100</maxLatency>
      </link>
     </links>
    </node>
    <node name="node3">
     <hostingHost name="host1"/>
     <functionalType type="webclient"/>
     <associatedNFFG name="nffg1"/>
     <links>
      <link name="link3" sourceNode="node3" destinationNode="node2">
       <minThroughput unit="Mbps">20.0</minThroughput>
       <maxLatency unit="ms">100</maxLatency>
      </link>
     </links>
    </node>
   </nodes>
  </nffg>
  <nffg name="nffg2">
   <deployTime>2017-11-11T10:00:00+01:00</deployTime>
   <nodes>
    <node name="node4">
     <hostingHost name="host2"/>
     <functionalType type="webclient"/>
     <associatedNFFG name= "nffg2"/>
     <links>
      <link name="link1" sourceNode="node4" destinationNode="node5">
       <minThroughput unit="Mbps">20.0</minThroughput>
       <maxLatency unit="ms">100</maxLatency>
      </link>
     </links>
    </node>
    <node name="node5">
     <hostingHost name="host2"/>
     <functionalType type="webserver"/>
     <associatedNFFG name="nffg2"/>
     <links>
      <link name="link2" sourceNode="node5" destinationNode="node4">
       <minThroughput unit="Mbps">20.0</minThroughput>
       <maxLatency unit="ms">100</maxLatency>
      </link>
     </links>
    </node>
   </nodes>
  </nffg>
 </deployedNFFGs>
</NFVSystem>
